### ISSUE TITLE
infrastructure: bucket improvements

### ISSUE THREAD

**Issue by imrehg** [nhsx/covid-chest-imaging-database#17]
Lifecycle policy for cleaning up unfinished uploads, something like:

```yaml
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            Status: Enabled
```

Add explicit rules for Cloudformation delete:

```yaml
    DeletionPolicy: Retain
```

The bucket wouldn't be deleted anyways (since not empty), but specifying this would allow the CFN delete to succeed just fine as the deletion would be marked as "known failure". And thus is cleaner.
